export const ENDPOINTS = {
  register: '/auth/register',
  login: '/auth/login',
  me: '/auth/me',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  updateProfile: '/auth/me',
  changePassword: '/auth/change-password',
  myLeads: '/leads/mine',
  myReviews: '/reviews/mine',
  vendors: '/vendors',
  vendorCities: '/vendors/cities',
  vendorBySlug: (slug) => `/vendors/${slug}`,
  vendorOwn: (vendorId) => `/vendors/${vendorId}/own`,
  vendorUpdate: (vendorId) => `/vendors/${vendorId}`,
  vendorLeads: (vendorId) => `/vendors/${vendorId}/leads`,
  leads: '/leads',
  reviews: '/reviews',
  vendorReviews: (vendorId) => `/reviews/${vendorId}`,
  uploadImage: '/upload/image',
  favorites: '/users/me/favorites',
  favoriteToggle: (vendorId) => `/users/me/favorites/${vendorId}`,
  blogList: '/blog',
  blogBySlug: (slug) => `/blog/${slug}`,
  altchaChallenge: '/altcha/challenge',
  contact: '/contact',

  // Admin
  adminStats: '/admin/stats',
  adminVendorsPending: '/admin/vendors/pending',
  adminVendors: '/admin/vendors',
  adminVendor: (id) => `/admin/vendors/${id}`,
  adminVendorApprove: (id) => `/admin/vendors/${id}/approve`,
  adminVendorReject: (id) => `/admin/vendors/${id}/reject`,
  adminVendorSuspend: (id) => `/admin/vendors/${id}/suspend`,
  adminVendorReactivate: (id) => `/admin/vendors/${id}/reactivate`,
  adminReviewsPending: '/admin/reviews/pending',
  adminReviews: '/admin/reviews',
  adminReviewApprove: (id) => `/admin/reviews/${id}/approve`,
  adminReviewReject: (id) => `/admin/reviews/${id}/reject`,
  adminReviewUnpublish: (id) => `/admin/reviews/${id}/unpublish`,
  adminBlogList: '/admin/blog',
  adminBlogCreate: '/admin/blog',
  adminBlogGet: (id) => `/admin/blog/${id}`,
  adminBlogUpdate: (id) => `/admin/blog/${id}`,
  adminBlogUnpublish: (id) => `/admin/blog/${id}/unpublish`,
  adminUsers: '/admin/users',
  adminUserUpdate: (id) => `/admin/users/${id}`,
  adminLeads: '/admin/leads',
  adminAuditLog: '/admin/audit-log',
};
